### ISSUE TITLE
`invalid chain id` exception during running `game-tui1` or `game-tui2` or even `game-tuio`

### ISSUE THREAD

**Issue by niktest** [ardanlabs/liarsdice#16]
Hi @ardan-bkennedy, 
I just wanted to start by saying thank you for your repository and all the hard work you've put in.
I managed to get the project deployed, but I've hit a roadblock trying to run the game engine.

I checked the presence and running of Engine by visiting `http://localhost:3000/v1/game/config` and got the successful response `{"network":"http://localhost:8545","chainId":1337,"contractId":"0x531130464929826c57bbbf989e44085a02eeb120"}`

During the lunching, `game-tui1` or `game-tui2` or even `game-tuio` gets the following error: `invalid chain id, got 0, exp 1337`.

I've checked the last dev logs and obtain the following logs:

```
SALES-API: 2024-07-16T12:31:19.20505814Z: logger.go:29: INFO: 22d82c42-c182-4aa7-8ecd-c3b80ae7e28a: request completed: path[/v1/game/config]: since[87.043µs]: method[GET]: remoteaddr[172.18.0.1:52968]: statuscode[200]
SALES-API: 2024-07-16T12:32:04.014438097Z: logger.go:25: INFO: b8def3c5-ac41-405d-8c2a-ca34445f5c80: request started: path[/v1/game/connect]: method[POST]: remoteaddr[172.18.0.1:34048]
SALES-API: 2024-07-16T12:32:04.014600352Z: gamegrp.go:501: INFO: b8def3c5-ac41-405d-8c2a-ca34445f5c80: validate signature: 20240716123204[20240716123204]: address[0x0070742ff6003c3e809e78d524f0fe5dcc5ba7f7]: signature[0xe0c4cd601dfa8303c0f90984b03386a0a6c9405962884e8ba0e615f7bc24df36579883f81981e4b6ac74c1205c2520bf2181c73fe8b24c1a8cbb69629ee593dc1c]: datetime[curtime]
SALES-API: 2024-07-16T12:32:04.014640396Z: main.go:54: INFO: b8def3c5-ac41-405d-8c2a-ca34445f5c80: ******* SEND ALERT ******
SALES-API: 2024-07-16T12:32:04.0146354Z: errors.go:21: ERROR: b8def3c5-ac41-405d-8c2a-ca34445f5c80: invalid chain id, got 0, exp 1337
SALES-API: 2024-07-16T12:32:04.014699583Z: logger.go:29: INFO: b8def3c5-ac41-405d-8c2a-ca34445f5c80: request completed: method[POST]: remoteaddr[172.18.0.1:34048]: since[266.018µs]: path[/v1/game/connect]: statuscode[400]
````

During the checking code, it's raising exception at `app/services/engine/handlers/gamegrp/gamegrp.go:507.`
```
	if dt.ChainID != chainID {
		return "", fmt.Errorf("invalid chain id, got %d, exp %d", dt.ChainID, chainID)
	}
```

But unfortunately, I can't get past this point at this moment.

@ardan-bkennedy I would really appreciate it if you could give me some hints or clues about what might be wrong with it. Or perhaps the recent changes in Ethereum have affected the project. Thank you!

**Comment by ardan-bkennedy** [comment]
I never expected anyone to try and run this. It is a work in progress.  I am getting that MCOPY error, which I fixed once with the smart contract project. So once I can today I will get this working again for me and look into your problem.

**Comment by ardan-bkennedy** [comment]
Pull latest. I merge the FE version I was working on. There is JS code there that can talk to a MetaMask wallet. During that work we added chain id to the data that needed to be signed and verified. This helps with making sure you don't access the wrong chain. That code somehow didn't make it back to the TUI. I have hardcoded the chain id in the TUI.

**Comment by ardan-bkennedy** [comment]
@niktest send me an email so we can talk. I want to know what you are doing with this code.

bill@ardanlabs.com
