### ISSUE TITLE
make geth-up: Fatal: bind: operation not supported

### ISSUE THREAD

**Issue by jontstaz** [ardanlabs/liarsdice#8]
Hi,

First of all very nice project you've got here. I've had a good look through the code and it really covers all bases. I wanted to test it out locally but I'm facing something strange with geth. When I run `make geth-up`, as suggested in the Wiki to do for step 1, I get the following error:
```
WARN [01-05|20:52:08.814] IPC opening failed url=zarf/ethereum/geth.ipc error="listen unix zarf/ethereum/geth.ipc: bind: operation not supported"

Fatal: Error starting protocol stack: listen unix zarf/ethereum/geth.ipc: bind: operation not supported
```

I've tried both the most recent unstable version of geth and the most recent stable version (1.10.26-stable) resulting in the same error for both. 

Am I missing something? I noticed that there's a warning for running Geth in --dev mode stating that networking is disabled but yet in the `make geth-up` command, you have added what looks like a number of networking-related parameters with the geth --dev command.

Thanks in advance,

**Comment by ardan-bkennedy** [comment]
We have worked hard to get this project working in K8s. I probably need to update the wiki now, but the project is in a bit of flux. I think in a month it will be very stable again.

If you can install KIND and Kubectl, you can get this running.

```
# To init your environment
make dev.setup.mac   or   make dev.setup.mac.arm64
make dev.docker

# To get the system running
make dev-up
make dev-update-apply

**Comment by ardan-bkennedy** [comment]
I did try the `make geth-up` command and it worked for me. 

```
$ geth version
Geth
Version: 1.10.26-stable
Architecture: arm64
Go Version: go1.19.3
Operating System: darwin
GOPATH=/Users/bill/code/go
GOROOT=
```

**Comment by ardan-bkennedy** [comment]
I have updated the wiki and provided better instructions. Please let me know if the system is working for you now.

**Comment by jontstaz** [comment]
Hey @ardan-bkennedy,
Thanks for updating the wiki. I installed KIND, Kubectl, Kustomize, Staticcheck and telepresence. However it's getting stuck on the `telepresence --context=kind-liars-game-cluster helm install` command, stating that `helm install` is an unrecognized argument within telepresence. 

EDIT: It was because I was using an outdated version of Telepresence. Here is the full output now so it looks like I've got the server working which is good! Thanks for the help:

```
kind create cluster \
      --image kindest/node:v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1 \
      --name liars-game-cluster \
      --config zarf/k8s/dev/kind-config.yaml
Creating cluster "liars-game-cluster" ...
 ✓ Ensuring node image (kindest/node:v1.25.3) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-liars-game-cluster"
You can now use your cluster with:

kubectl cluster-info --context kind-liars-game-cluster

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
kubectl wait --timeout=120s --namespace=local-path-storage --for=condition=Available deployment/local-path-provisioner
deployment.apps/local-path-provisioner condition met
kind load docker-image docker.io/datawire/tel2:2.10.1 --name liars-game-cluster
Image: "" with ID "sha256:fdfea19bfd77fee56900257eb59c659ae160b10bf11f5011f8bdf99a3257f9f1" not yet present on node "liars-game-cluster-control-plane", loading...
kind load docker-image ethereum/client-go:stable --name liars-game-cluster
Image: "" with ID "sha256:c16c2e0da3257909f0c460a844611cdc9289fa50d3ee9629d174c25f350e873a" not yet present on node "liars-game-cluster-control-plane", loading...
telepresence --context=kind-liars-game-cluster helm install
Telepresence Daemons disconnecting...done

Traffic Manager installed successfully
telepresence --context=kind-liars-game-cluster connect
Connected to context kind-liars-game-cluster (https://127.0.0.1:46613)
```

**Comment by ardan-bkennedy** [comment]
What version of `datawire/blackbird/telepresence` do you have installed?

**Comment by ardan-bkennedy** [comment]
Just read the second post. Very cool
